# Generated by Django 5.1.7 on 2025-04-10 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='mobile_number',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
